// src/App.vue
<template>
  <div class="column">
    <navbar></navbar>
    <full-page ref="fullpage" :options="options" id="fullpage">
      <div class="section">
        <main-view></main-view>
      </div>
      <div class="section">
        <experience></experience>
      </div>
      <div class="section">
        <portfolio></portfolio>
      </div>
      <div class="section">
        <contact></contact>
      </div>
    </full-page>
  </div>
</template>

<script>
import Navbar from "./components/Navbar.vue";
import MainView from "./screens/Main.vue";
import Contact from "./screens/Contact.vue";
import Experience from "./screens/Experience.vue";
import Portfolio from "./screens/Portfolio.vue";

export default {
  name: "App",
  data() {
    return {
      options: {
      }
    }
  },
  components: {
    Navbar,
    MainView,
    Experience,
    Portfolio,
    Contact,
  },
};
</script>

<style lang="scss">
@import "./scss/application";

.section {
  min-height: 100vh;
  > *:first-child {
    padding: 40px 70px 40px 140px;
    position: relative;
  
    @media screen and (max-width: 900px) {
      padding: 40px 10px 40px 70px;
    }
  }
}
</style>

// app/page.tsx
import Navbar from './components/Navbar';
import MainSection from './components/MainSection';
import ExperienceSection from './components/ExperienceSection';
import PortfolioSection from './components/PortfolioSection';
import ContactSection from './components/ContactSection';

export default function Home() {
  return (
    <div className="flex flex-row">
      <Navbar />
      <div className="flex-1 h-screen overflow-y-scroll snap-y snap-mandatory">
        <section className="min-h-screen snap-start [&>*:first-child]:p-[40px_70px_40px_140px] [&>*:first-child]:relative [&>*:first-child]:min-h-screen max-[900px]:[&>*:first-child]:p-[40px_10px_40px_70px]" id="main">
          <MainSection />
        </section>
        <section className="min-h-screen snap-start [&>*:first-child]:p-[40px_70px_40px_140px] [&>*:first-child]:relative [&>*:first-child]:min-h-screen max-[900px]:[&>*:first-child]:p-[40px_10px_40px_70px]" id="experience">
          <ExperienceSection />
        </section>
        <section className="min-h-screen snap-start [&>*:first-child]:p-[40px_70px_40px_140px] [&>*:first-child]:relative [&>*:first-child]:min-h-screen max-[900px]:[&>*:first-child]:p-[40px_10px_40px_70px]" id="portfolio">
          <PortfolioSection />
        </section>
        <section className="min-h-screen snap-start [&>*:first-child]:p-[40px_70px_40px_140px] [&>*:first-child]:relative [&>*:first-child]:min-h-screen max-[900px]:[&>*:first-child]:p-[40px_10px_40px_70px]" id="contact">
          <ContactSection />
        </section>
      </div>
    </div>
  );
}
