// app/components/Footer.tsx
import styles from './Footer.module.css';

export default function Footer() {
  return (
    <footer className={styles.container}>
      <span className="full-width align-text-center">
        Feel free to check{' '}
        <a
          className="link"
          href="https://www.github.com/FrankIglesias/portfolio"
          target="_blank"
          rel="noopener noreferrer"
        >
          the repository
        </a>{' '}
        on Github.
      </span>
    </footer>
  );
}

// src/components/Footer.vue
<template>
  <footer>
    <span class="full-width align-text-center"
      >Feel free to check
      <a
        class="link"
        href="www.github.com/FrankIglesias/portfolio"
        target="_blank"
        >the repository</a
      >
      on Github.</span
    >
  </footer>
</template>

<script>
export default {};
</script>


<style lang="scss" scoped>
</style>
